### ISSUE TITLE
Service Menu => Brick Menu 로 변환

### ISSUE THREAD

**Issue by sola-scriptura-zz** [adfontes/stigma2#1]
서비스 메뉴는 RHS 용 메뉴가 아니기 때문에 제거하고 Brick 모니터링 메뉴로 변환 합니다.

각 Brick 에 대하여 Profile 기능을 켜고 끌 수 있게 하고, Profile 된 내역에 대하여 데이터를 수집하여 보여 줄 수 있도록 합니다. 

일반적으로 다음과 같은 내역을 정리하여 보여 줄 수 있도록 정리 하여야 합니다. 
# gluster volume profile VOLNAME info

For example, to see the I/O information on test-volume:
# gluster volume profile test-volume info

Brick: Test:/export/2

Cumulative Stats:
Block Size:     1b+ 32b+    64b+
Read:   0   0   0
Write   908 28  8
Block Size:     128b+   256b+   512b+
Read:   0   6   4
Write   5   23  16
Block Size:     1024b+  2048b+  4096b+
Read:   0   52  17
Write   15  120 863
Block Size:     8192b+  16384b+ 32768b+
Read:   52  8   34
Write   234 134 286
Block Size:         65536b+ 131072b+
Read:       118 622
Write       1341    594
%-latency   Avg-latency Min-Latency Max-Latency calls   Fop
4.82    1132.28 21.00   800970.00   4575    WRITE
5.70    156.47  9.00    665085.00   39163   READDIRP
11.35   315.02  9.00    1433947.00  38698   LOOKUP
11.88   1729.34 21.00   2569638.00  7382    FXATTROP
47.35   104235.02   2485.00 7789367.00  488 FSYNC

---

---

Duration :  335
BytesRead  :    94505058
BytesWritten :  195571980

**Comment by ilyf28** [comment]
- Bricks 메뉴로 변환 완료
- Brick Detail 페이지에서 profile info 보여지도록 수정 완료

**Comment by ilyf28** [comment]
- http://106.243.87.166:6060/stigma2/status/bricks 에서 확인 가능 (단, URL 직접 입력시 Index 페이지로 이동)
