### ISSUE TITLE
[SIDE MENU > Report] 메뉴의 필요 여부

### ISSUE THREAD

**Issue by ilyf28** [adfontes/stigma2#10]
- 현재 Demo 페이지에서 [Graph], [Log] 메뉴가 있는데, 각각의 역할과 기능
- 필요 유무 판별

**Comment by sola-scriptura-zz** [comment]
Graph 와 Log 는 실시간으로 세부 상황을 확인하기 위해서 필요하고,

Report 는 정기점검 혹은 보고 자료 만들때 필요한 분석 데이터를 생성해야 하기 때문에 별도로 필요합니다.

**Comment by ilyf28** [comment]
- 확인 완료
