### ISSUE TITLE
Host 와 Node 명칭 일치

### ISSUE THREAD

**Issue by sola-scriptura-zz** [adfontes/stigma2#2]
모든 호스트를 Node 로 변환하여 일치 시킴

**Comment by ilyf28** [comment]
- Demo 페이지의 Side Menu 에 [Host] 항목이 있습니다

이것 또한 Node로 변경되는 것이 맞나요?
- Node List column중 변경될 부분이 있을까요?
- Node List에서 Name(현재 Host name)을 클릭하면 Detail 화면으로 이동합니다

Detail에서 보여줄 화면은 다시 구상하겠습니다

**Comment by ilyf28** [comment]
- Node 로 변환 완료
