### ISSUE TITLE
Volume Usage 를 원그래프 형태로 변환

### ISSUE THREAD

**Issue by sola-scriptura-zz** [adfontes/stigma2#4]
Volume usage 를 원그래프 형태로 변환

**Comment by ilyf28** [comment]
example.

http://www.highcharts.com/demo/gauge-solid

http://www.highcharts.com/demo/pie-basic

**Comment by ilyf28** [comment]
- 5초 간격으로 request call 실행한 후 결과값을 출력함
  (test page : http://106.243.87.166:6060/stigma2/status/nodes/1)
